services:
  - type: web
    name: vendecerca-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
        value: 25MB
      - key: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
        value: 25MB
      - key: JAVA_OPTS
        value: -XX:MaxRAMPercentage=75.0
