spring.application.name=VendeCercaAPI
server.port=8080
spring.datasource.username=admin
spring.datasource.password=EuHIRRqxx79IEmoi6zHkvvzItqQorQ
spring.datasource.url=jdbc:postgresql://mx-central-1.fbd47bae-7ad7-4062-9db7-7cc005fc9793.aws.yugabyte.cloud:5433/VendeCerca
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/documentacion/swagger-ui.html
springdoc.path-to-match=/api/v1/direcciones/**, /api/v1/usuarios/**, /api/v1/feedbacks/**, /api/v1/chats/**, /api/v1/mensajes/**, /api/v1/productos-servicios/**, /api/v1/imagenes/**, /api/v1/personas/**, /api/v1/negocios/**, /api/v1/tipos-producto/**, /api/v1/tipos-usuarios/**, /api/v1/mails/**, /api/v1/archivos/**
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=snowsnows1234883@gmail.com
spring.mail.password=yeqzmwqoqzweqtaz
