CREATE TABLE IF NOT EXISTS TipoUsuario (
    tip_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tip_nombre VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS TipoProducto (
    tpr_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tpr_nombre VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Usuario (
    usu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usu_nombre VARCHAR(15) NOT NULL,
    usu_password VARCHAR(255) NOT NULL,
    usu_activo BOOLEAN NOT NULL DEFAULT TRUE,
    tip_id BIGINT,
    CONSTRAINT fk_usuario_tipousuario
        FOREIGN KEY (tip_id) REFERENCES TipoUsuario (tip_id)
);

CREATE TABLE IF NOT EXISTS Persona (
    per_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    per_nombrecompleto VARCHAR(50) NOT NULL,
    per_telefono VARCHAR(10) NOT NULL,
    per_correo VARCHAR(50) NOT NULL,
    per_fecha TIMESTAMPTZ NOT NULL,
    usu_id BIGINT UNIQUE,
    CONSTRAINT fk_persona_usuario
        FOREIGN KEY (usu_id) REFERENCES Usuario (usu_id)
);

CREATE TABLE IF NOT EXISTS Direccion (
    dir_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dir_colonia VARCHAR(100) NOT NULL,
    dir_calle VARCHAR(100) NOT NULL,
    dir_numero VARCHAR(20),
    dir_indicaciones VARCHAR(300),
    dir_cp INTEGER NOT NULL,
    dir_latitud NUMERIC(38, 2),
    dir_longitud NUMERIC(38, 2),
    dir_ultimaubicacion TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS Negocio (
    neg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    neg_nombre VARCHAR(50) NOT NULL,
    neg_descripcion VARCHAR(300) NOT NULL,
    neg_fecha TIMESTAMPTZ NOT NULL,
    neg_activo BOOLEAN NOT NULL DEFAULT TRUE,
    neg_ambulante BOOLEAN NOT NULL,
    neg_abierto BOOLEAN NOT NULL,
    per_id BIGINT,
    dir_id BIGINT,
    CONSTRAINT fk_negocio_persona
        FOREIGN KEY (per_id) REFERENCES Persona (per_id),
    CONSTRAINT fk_negocio_direccion
        FOREIGN KEY (dir_id) REFERENCES Direccion (dir_id)
);

CREATE TABLE IF NOT EXISTS ProductoServicio (
    pro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    neg_id BIGINT,
    pro_nombre VARCHAR(50) NOT NULL,
    pro_descripcion VARCHAR(300) NOT NULL,
    pro_fecha TIMESTAMPTZ NOT NULL,
    pro_activo BOOLEAN NOT NULL DEFAULT TRUE,
    pro_precio NUMERIC(38, 2) NOT NULL,
    tpr_id BIGINT,
    pro_cantidad INTEGER NOT NULL,
    CONSTRAINT fk_productoservicio_negocio
        FOREIGN KEY (neg_id) REFERENCES Negocio (neg_id),
    CONSTRAINT fk_productoservicio_tipoproducto
        FOREIGN KEY (tpr_id) REFERENCES TipoProducto (tpr_id)
);

CREATE TABLE IF NOT EXISTS Imagen (
    img_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    neg_id BIGINT,
    per_id BIGINT UNIQUE,
    pro_id BIGINT UNIQUE,
    img_url VARCHAR(255) NOT NULL,
    img_principal BOOLEAN,
    CONSTRAINT fk_imagen_negocio
        FOREIGN KEY (neg_id) REFERENCES Negocio (neg_id),
    CONSTRAINT fk_imagen_persona
        FOREIGN KEY (per_id) REFERENCES Persona (per_id),
    CONSTRAINT fk_imagen_productoservicio
        FOREIGN KEY (pro_id) REFERENCES ProductoServicio (pro_id)
);

CREATE TABLE IF NOT EXISTS Feedback (
    fed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fed_texto VARCHAR(255) NOT NULL,
    fed_estrella INTEGER NOT NULL,
    fed_fecha TIMESTAMPTZ NOT NULL,
    per_id BIGINT,
    neg_id BIGINT,
    CONSTRAINT fk_feedback_persona
        FOREIGN KEY (per_id) REFERENCES Persona (per_id),
    CONSTRAINT fk_feedback_negocio
        FOREIGN KEY (neg_id) REFERENCES Negocio (neg_id)
);

CREATE TABLE IF NOT EXISTS Chat (
    cha_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    per_idcomprador BIGINT,
    per_idvendedor BIGINT,
    neg_id BIGINT,
    CONSTRAINT fk_chat_comprador
        FOREIGN KEY (per_idcomprador) REFERENCES Persona (per_id),
    CONSTRAINT fk_chat_vendedor
        FOREIGN KEY (per_idvendedor) REFERENCES Persona (per_id),
    CONSTRAINT fk_chat_negocio
        FOREIGN KEY (neg_id) REFERENCES Negocio (neg_id)
);

CREATE TABLE IF NOT EXISTS Mensaje (
    men_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    men_texto VARCHAR(255) NOT NULL,
    men_fecha TIMESTAMPTZ NOT NULL,
    men_leido BOOLEAN NOT NULL DEFAULT FALSE,
    per_idemisor BIGINT,
    cha_id BIGINT,
    CONSTRAINT fk_mensaje_emisor
        FOREIGN KEY (per_idemisor) REFERENCES Persona (per_id),
    CONSTRAINT fk_mensaje_chat
        FOREIGN KEY (cha_id) REFERENCES Chat (cha_id)
);

CREATE TABLE IF NOT EXISTS Archivo (
    idArchivo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreArchivo VARCHAR(255),
    tipoArchivo VARCHAR(255),
    datosArchivo BYTEA
);

CREATE INDEX IF NOT EXISTS idx_usuario_tip_id ON Usuario (tip_id);
CREATE INDEX IF NOT EXISTS idx_persona_usu_id ON Persona (usu_id);
CREATE INDEX IF NOT EXISTS idx_negocio_per_id ON Negocio (per_id);
CREATE INDEX IF NOT EXISTS idx_negocio_dir_id ON Negocio (dir_id);
CREATE INDEX IF NOT EXISTS idx_producto_neg_id ON ProductoServicio (neg_id);
CREATE INDEX IF NOT EXISTS idx_producto_tpr_id ON ProductoServicio (tpr_id);
CREATE INDEX IF NOT EXISTS idx_imagen_neg_id ON Imagen (neg_id);
CREATE INDEX IF NOT EXISTS idx_feedback_per_id ON Feedback (per_id);
CREATE INDEX IF NOT EXISTS idx_feedback_neg_id ON Feedback (neg_id);
CREATE INDEX IF NOT EXISTS idx_chat_comprador ON Chat (per_idcomprador);
CREATE INDEX IF NOT EXISTS idx_chat_vendedor ON Chat (per_idvendedor);
CREATE INDEX IF NOT EXISTS idx_chat_neg_id ON Chat (neg_id);
CREATE INDEX IF NOT EXISTS idx_mensaje_emisor ON Mensaje (per_idemisor);
CREATE INDEX IF NOT EXISTS idx_mensaje_cha_id ON Mensaje (cha_id);

INSERT INTO TipoUsuario (tip_nombre)
SELECT 'cliente'
WHERE NOT EXISTS (SELECT 1 FROM TipoUsuario WHERE tip_nombre = 'cliente');

INSERT INTO TipoUsuario (tip_nombre)
SELECT 'vendedor'
WHERE NOT EXISTS (SELECT 1 FROM TipoUsuario WHERE tip_nombre = 'vendedor');

INSERT INTO TipoProducto (tpr_nombre)
SELECT 'producto'
WHERE NOT EXISTS (SELECT 1 FROM TipoProducto WHERE tpr_nombre = 'producto');

INSERT INTO TipoProducto (tpr_nombre)
SELECT 'servicio'
WHERE NOT EXISTS (SELECT 1 FROM TipoProducto WHERE tpr_nombre = 'servicio');

INSERT INTO Direccion (
    dir_colonia,
    dir_calle,
    dir_numero,
    dir_indicaciones,
    dir_cp,
    dir_latitud,
    dir_longitud,
    dir_ultimaubicacion
)
SELECT
    'Centro',
    'Av. Principal',
    '123',
    'Frente al parque',
    76000,
    20.5888,
    -100.3899,
    NOW()
WHERE NOT EXISTS (SELECT 1 FROM Direccion WHERE dir_colonia = 'Centro' AND dir_calle = 'Av. Principal');
